version: '3.3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.ProductionConfig
      - AWS_ACCESS_KEY_ID=AKIAIPW56LY27INLVM5Q
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=eu-west-2
      - DATABASE_URL=https://dynamodb.eu-west-2.amazonaws.com
      - MSAL_APP_ID=b56b6ea3-6322-415e-a9b3-72ab82fc4169
      - MSAL_APP_SECRET=edKOV9_NBkJ1-7oUI5F_mDRkxP7ko.hPmq
      - MSAL_REDIRECT=http://localhost:5000/subscribe/outlook
      - GOOGLE_APP_ID=1096007776934-i337kchlc6n4ui3lml7n15p8fhs8va9e.apps.googleusercontent.com
      - GOOGLE_APP_SECRET=l4IJ8QZvW49N4-lESLhqA2Hy
      - GOOGLE_REDIRECT=http://localhost:5000/subscribe/gmail


